# Name of your site (displayed in the header)
name: Sol Labs
author: Cyan Raphael Yi
# Short bio or description (displayed in the header)
description: Sollabs Main Page

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /static/img/profile.jpg
email: cyan.r.yi@gmail.com
github: https://github.com/CyanRYi

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

facebook_app: 122275605125275
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-135681883-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.sollabs.tech

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

# The release of Jekyll Now that you're using
version: v3.7.4

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
markdown: kramdown
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: true

urls:
  - text: About Me
    url: /about/
  - text: XML Feed
    url: /feed.xml

permalink: /:title

collections:
  language:
    output: true
  tag:
    output: true
    permalink: /tag/:name/
  category:
    output: true
    permalink: /category/:name/
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: tag
    values:
      layout: tag_list
  - scope:
      path: ''
      type: category
    values:
      layout: category_list
  - scope:
      path: '_posts/en'
    values:
      language: en
      permalink: /en/:title
  - scope:
      path: '_posts/ko'
    values:
      language: ko

